server:
  interface: 0.0.0.0
  interface: ::0
  port: 53

  # Autoriser uniquement le LAN 192.168.100.0/24 + localhost
  access-control: 127.0.0.0/8 allow
  access-control: ::1 allow
  access-control: 192.168.100.0/24 allow
  access-control: 0.0.0.0/0 refuse
  access-control: ::0/0 refuse

  # Durcissement basique
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  use-caps-for-id: yes

  # Cache
  prefetch: yes
  cache-min-ttl: 300
  cache-max-ttl: 86400

  # Logs simples
  verbosity: 1

# Domaine interne de projet
local-zone: "secos-gr8.lan." static

# Enregistrements internes (au moins admin + dns)
local-data: "admin.secos-gr8.lan. IN A 192.168.100.120"
local-data: "dns.secos-gr8.lan.   IN A 192.168.100.136"
